version: '3.8'

services:

  prometheus:
    user: "0:0"
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "0:0"
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/datasources # provisions prometheus as data source
      - ./grafana-db/:/var/lib/grafana # persist Grafana database
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
      - GF_AUTH_BASIC_ENABLED=false # removes login 2/2
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode #enables new alert creation flow
    depends_on:
      - prometheus

networks:
  monitoring:

volumes:
  grafana-db:
